apiVersion: v1
kind: Service
metadata:
  name: ubuntu-nginx-service-1
  namespace: monitoring
spec:
  selector:
    app: ubuntu-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
